Blog_System/urls.py
from django.contrib import admin
from django.urls import path, include
from search import views # import views จากแอพ search เพื่อเอา path login, logout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('search.urls')),
    path('login/', views.my_login, name='login'),
    path('logout/', views.my_logout, name='logout'),
]

search/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.my_register, name='register'),
    path('creator/', views.creator, name='creator'),
    path('post/', views.post, name='post'),
    path('changepass/', views.change_pass, name='change_pass'),
    path('blog/<int:num>/', views.blog, name='blog'),
    path('blog/<int:blog>/<int:com_remv>/', views.com_remove, name='com_remove'),
    path('postremove/<int:post_id>/', views.post_remove, name='post_remove'),
    path('editblog/<int:blogedit>/', views.edit_blog, name='edit_blog'),
    path('editcom/<int:comedit>/', views.edit_com, name='edit_com'),
    path('status/<int:change_status>/', views.status, name='status'),
]

blogger/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    create_time = models.DateTimeField(blank=True)
    update_time = models.DateTimeField(blank=True)
    status = models.BooleanField()
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Comment(models.Model):
    content = models.TextField()
    create_time = models.DateTimeField()
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

search/models.py
from django.db import models

# Create your models here.

search/views.py
from builtins import object
from datetime import datetime
from fnmatch import filter
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import Group, User
from django.shortcuts import *
from django.db.models import Count
from blogger.models import Comment, Post
from django.core.exceptions import ObjectDoesNotExist


def index(request):
    if request.method == 'POST':
        blog_name = request.POST.get('blog')

        # -------- แสดงเฉพาะบทความที่ไม่ถูกซ่อน ----------
        if request.user.is_superuser:
            # Blogger แสดงทุกบทความ
            post_all = Post.objects.filter(
                title__icontains=blog_name
            )
        else:
            post_all = Post.objects.filter(
                title__icontains=blog_name,
                status=True
            )
        # --------------------------------------------
        
        # -------- นับความคิดเห็นของแต่ละบทความ ----------
        com = Post.objects.annotate(Count('comment'))
        com = com.values_list('id', 'comment__count')
        # --------------------------------------------

        context = {
            'blog_name': "ผลลัพธ์การค้นหา : " + blog_name,
            'post_all': post_all,
            'com': com,
            'sign_page': "sign_page",
            'login_page': "login_page"
        }
        return render(request, 'search/index.html', context)

    # -------- แสดงเฉพาะบทความที่ไม่ถูกซ่อน ----------
    if request.user.is_superuser:
        # Blogger แสดงทุกบทความ
        post_all = Post.objects.all().order_by('id')
    else:
        post_all = Post.objects.filter(status=True).order_by('id')
    # --------------------------------------------

    # -------- นับความคิดเห็นของแต่ละบทความ ----------
    com = Post.objects.annotate(Count('comment'))
    com = com.values_list('id', 'comment__count')
    # --------------------------------------------

    context = {
        'post_all': post_all,
        'com': com,
        'sign_page': "sign_page",
        'login_page': "login_page"
    }
    return render(request, 'search/index.html', context)

def my_register(request):
    if request.method == 'POST':

        # ----------------- สร้าง user ใหม่แล้วนำเข้ากลุ่มผู้ชม ( audience ) -----------------
        try:
            user = User.objects.get(username=request.POST.get('username'))
        except ObjectDoesNotExist:
            user = None
        if user:
            context = {
                'error': "กรุณาตั้ง username ใหม่",
                'sign_page': "sign_page",
                'username': request.POST.get('username'),
                'password': request.POST.get('password'),
                'first_name': request.POST.get('first_name'),
                'last_name': request.POST.get('last_name'),
                'email': request.POST.get('email')
            }
            return render(request, 'search/signup.html', context)
        else:
            user = User.objects.create_user(
                username=request.POST.get('username'),
                password=request.POST.get('password'),
                first_name=request.POST.get('first_name'),
                last_name=request.POST.get('last_name'),
                email=request.POST.get('email')
            )
            group = Group.objects.get(name='audience') # นำเข้ากลุ่ม
            user.groups.add(group)
            user.save()
            return redirect('login')
        # -----------------------------------------------------------------------------

    return render(request, 'search/signup.html', context={'sign_page': "sign_page"})

def my_login(request):
    context = dict()
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        # --------------- เช็คว่า username, password มีอยู่ในข้อมูลหรือไม่ ----------------
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            next_url = request.POST.get('next_url')
            if next_url:
                return redirect(next_url)
            else:
                return redirect('index')
        else: # ไม่มีอยู่ในข้อมูล
            context = {
                'username': username,
                'password': password,
                'error': "ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้องกรุณากรอกอีกครั้ง",
                'login_page': "login_page"
            }
            return render(request, 'search/login.html', context)
        # -------------------------------------------------------------------------
        

    # -------- เมื่อมีการส่ง request next มา ----------
    next_url = request.GET.get('next')
    if next_url:
        context['next_url'] = next_url
    # --------------------------------------------

    context['login_page'] = "login_page"
    return render(request, 'search/login.html', context)

@login_required
def my_logout(request):
    logout(request)
    return redirect('login')

def creator(request):
    context = {
        'sign_page': "sign_page",
        'login_page': "login_page"
    }
    return render(request, 'search/creator.html', context)

def blog(request, num):
    if request.method == 'POST':

        # ----------------- การแสดงความคิดเห็น -----------------
        com = Comment(
            content=request.POST.get('content'),
            create_time=datetime.now(),
            user_id_id=request.user.id,
            post_id_id=num
        )
        com.save()
        blog = Post.objects.get(pk=num)
        com = Comment.objects.filter(post_id_id=num)
        context = {
            'blog': blog,
            'com': com
        }
        # ----------------------------------------------------

        return render(request, 'search/blog.html', context)

    # ------- ดึงข้อมูลมาจากตัวแปร num เป็น id ของ blog ------
    blog = Post.objects.get(pk=num)
    com = Comment.objects.filter(post_id_id=num)
    # ---------------------------------------------------

    context = {
        'blog': blog,
        'com': com,
        'sign_page': "sign_page",
        'login_page': "login_page"
    }
    return render(request, 'search/blog.html', context)

@login_required
@permission_required('blogger.change_post')
def edit_blog(request, blogedit):
    if request.method == 'POST':

        # ----- รับ request เช็คดูว่าบทความถูกซ่อนหรือไม่ -----
        if request.POST.get('checkbox') == "Hide":
            status = False
        else:
            status = True
        # ----------------------------------------------
        
        # ---------- แก้ไขความคิดเห็น ( อัพเดท ) ----------
        blog = Post.objects.get(pk=blogedit)
        blog.title = request.POST.get('title')
        blog.content = request.POST.get('content')
        blog.update_time = datetime.now()
        blog.status = status
        blog.save()
        # ----------------------------------------------

        return render(request, 'search/blog.html', context={'blog': blog})
    
    # ดึงข้อมูลบทความตามตัวแปรที่รับเข้ามา ( blogedit )
    blog = Post.objects.get(pk=blogedit)
    # ------------------------------------------

    return render(request, 'search/edit_blog.html', context={'blog': blog})

@login_required
@permission_required('blogger.add_post')
def post(request):
    if request.method == 'POST':

        # ----- รับ request เช็คดูว่าบทความถูกซ่อนหรือไม่ -----
        if request.POST.get('checkbox') == "Hide":
            status = False
        else:
            status = True
        # ----------------------------------------------

        # --------------- เพิ่มบทความใหม่ -----------------
        post = Post(
            user_id_id=1,
            title=request.POST.get('title'),
            content=request.POST.get('content'),
            create_time=datetime.now(),
            update_time = datetime.now(),
            status=status,
        )
        post.save()
        # ----------------------------------------------

        return render(request, 'search/blog.html', context={'blog': post})

    return render(request, 'search/post.html')

@login_required
@permission_required('blogger.change_comment')
def edit_com(request, comedit):
    if request.method == 'POST':
        
        # ------- แก้ไขความคิดเห็นตามตัวแปร comedit ---------
        com_new = Comment.objects.get(pk=comedit)
        com_new.content = request.POST.get('content')
        com_new.save()
        # ------------------------------------------------
        
        # ------------ ดึงข้อมูลบทความตาม id ของ Comment ----------------
        blog = Post.objects.get(pk=com_new.post_id.id)
        com = Comment.objects.filter(post_id_id=com_new.post_id.id)
        # -------------------------------------------------------------

        context = {
            'blog': blog,
            'com': com
        }
        return render(request, 'search/blog.html', context)

    # --- ดึงข้อมูล Comment ตามตัวแปร comedit ---
    com = Comment.objects.get(pk=comedit)
    # ---------------------------------------

    return render(request, 'search/edit_com.html', context={'com': com})

@login_required
@permission_required('blogger.delete_comment')
def com_remove(request, blog, com_remv):
    
    # ----------- ลบความคิดเห็น --------------
    com = Comment.objects.get(pk=com_remv)
    com.delete()
    # --------------------------------------

    # ----------- ดึงข้อมูลบทความตามตัวแปร blog ----------
    blog = Post.objects.get(pk=blog)
    all_com = Comment.objects.filter(post_id_id=blog)
    # -------------------------------------------------

    context = {
        'blog': blog,
        'com': all_com,
        'sign_page': "sign_page",
        'login_page': "login_page"
    }
    return render(request, 'search/blog.html', context)

@login_required
@permission_required('blogger.delete_post')
def post_remove(request, post_id):

    # ----------- ลบบทความ ---------------

search/templates/search/blog.html
{% extends "public_base.html" %}
{% load static %}

{% block content %}
<form action="{% url 'blog' blog.id %}" method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="form-group col-md-12 p-3 mt-3 card shadow bg-white rounded" style="width: 20rem;">
            <div class="row p-3 mr-1 ml-1 mt-1 mb-1">
                <div class="col-md-9">
                    <h3>{{ blog.title }}
                        {% comment %} ------ แสดง icon เพื่อบอกว่าบทความแสดงอยู่หรือไม่ ------ {% endcomment %}
                        {% if blog.status == False and user.is_superuser %}
                            <img src="{% static '/photo/hide.png' %}" width="30px">
                        {% endif %}
                        {% comment %} -------------------------------------------------- {% endcomment %}
                    </h3>
                </div>
                <div class="col-md-3 text-right">
                    {% comment %} -------------------------------------------- เฉพาะคนที่มีสิทธิ์แก้ไขบทความ -------------------------------------------- {% endcomment %}
                    {% if perms.blogger.change_post %}
                        <div class="row">
                            <div class="col-md-10" style="padding-right: 0;">
                            <a href="{% url 'edit_blog' blog.id %}"><img src="{% static '/photo/edit.png' %}" width="30px"></a>
                            </div>
                            <div class="col-md-2">
                            <a href="{% url 'post_remove' blog.id %}" onclick="remove()"><img src="{% static '/photo/remove.png' %}" width="30px"></a>
                            </div>
                        </div>
                    {% endif %}
                    {% comment %} ----------------------------------------------------------------------------------------------------------------- {% endcomment %}
                </div>
                <div class="col-md-12">
                    <hr>
                    <p>{{ blog.content }}</P>
                    <small class="font-italic text-right form-text text-muted">{{ blog.create_time }}</small>
                </div>
            </div>
        </div>
        <div class="form-group col-md-12 p-3 card shadow bg-white rounded" style="width: 20rem;">
            <div class="row p-3 mr-1 ml-1">
                <div class="col-md-12">
                    {% comment %} เช็คว่ามี Comment ในบทความนั้นๆหรือไม่ {% endcomment %}
                    {% if com.count > 0 %}
                        <h5>Comment</h5>
                    {% else %}
                        <h5>No Comment</h5>
                    {% endif %}
                    {% comment %} ------------------------------- {% endcomment %}
                </div>
                {% comment %} ---------------------------------------------------- loop ดึงข้อมูลความคิดเห็นจาก QuerySet ---------------------------------------------------- {% endcomment %}
                {% for i in com %}
                    <div class="col-md-8 card bg-white p-3 m-2">
                        <div class="row">
                            <div class="col-md-8" style="padding-right: 0;">
                                <p>{{ i.content }}</p>
                            </div>
                            <div class="col-md-4">
                                <div class="row">
                                    <div class="col-md-10 text-right" style="padding-right: 2;">
                                        {% if request.user.username ==  i.user_id.username %}
                                            <a href="{% url 'edit_com' i.id %}"><img src="{% static '/photo/edit.png' %}" width="20px"></a>
                                        {% endif %}
                                    </div>
                                    <div class="col-md-2" style="padding-left: 3;">
                                        {% if request.user.username ==  i.user_id.username or user.is_superuser %}
                                            <a href="{% url 'com_remove' blog.id i.id %}" onclick="popup()"><img src="{% static '/photo/remove.png' %}" width="20px"></a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <small class="font-italic text-right form-text text-muted">โดย: {{ i.user_id.username }} เมื่อ: {{ i.create_time }}</small>
                    </div>
                {% endfor %}
                {% comment %} -------------------------------------------------------------------------------------------------------------------------------------------  {% endcomment %}
                
                {% comment %} ----------------------------- แสดงเฉพาะคนที่มีสิทธิ์แสดงความคิดเห็น ----------------------------- {% endcomment %}
                {% if perms.blogger.add_comment %}
                    <div class="col-md-8 m-2" style="padding-right: 0; padding-left: 0; margin-left: 8;">
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="content" required></textarea>
                    </div>
                    <div class="col-md-8 ml-2">
                        <div class="row">
                            <div class="col-md-6" style="padding-left: 0;">
                                <small class="font-italic form-text text-muted">แสดงความคิดเห็นโดย {{ request.user.username }}</small>
                            </div>
                            <div class="col-md-6 text-right" style="padding-right: 0;">
                                <button type="submit" class="btn btn-outline-warning mb-2">แสดงความคิดเห็น</button>
                            </div>
                        </div>
                    </div>
                {% endif %}
                {% comment %} ------------------------------------------------------------------------------------------ {% endcomment %}
            </div>
        </div>
    </div>
</form>
<script>
    function popup(){
        alert('ลบความคิดเห็นสำเร็จ')
    }
</script>
{% endblock %}

search/templates/search/changepass.html
{% extends "public_base.html" %}
{% block content %}
    <div class="p-5 text-center">
        <h2>เปลี่ยนรหัสผ่าน</h2>
        <small class="form-text text-muted">Username : {{ request.user.username }}</small>
    </div>
    <div class="row p-3">
        <div class="col-sm-4">
        </div>
        <div class="col-sm-4">
            <form action="{% url 'change_pass' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="exampleInputEmail1">New Password ( รหัสผ่านใหม่ )</label>
                    <input type="password" class="form-control" id="exampleInputEmail1" placeholder="รหัสผ่าน" name="password1"
                    {% if error %}
                        value="{{ password1 }}"
                    {% endif %} required>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Confirm Password ( ยืนยันรหัสผ่าน )</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="กรอกรหัสผ่านอีกครั้ง" name="password2"
                    {% if error %}
                        value="{{ password2 }}"
                    {% endif %} required>
                </div>
                <input type="hidden" name="next_url" value="{{ next_url }}">
                    {% comment %} ------------------------------------ ถ้ามีการส่ง error กลับมา ( รหัสผ่านไม่ตรงกัน ) ------------------------------------ {% endcomment %}
                    {% if error %}
                        <small class="form-text text-danger text-center" style="margin-bottom: 4;">{{ error }}</small>
                    {% else %}
                        <small class="form-text text-muted text-center" style="margin-bottom: 4;">ตรวจสอบรหัสผ่านให้แน่ใจก่อนเปลี่ยนรหัสผ่าน</small>
                    {% endif %}
                    {% comment %} ----------------------------------------------------------------------------------------------------------------- {% endcomment %}
                <button type="submit" class="btn btn-outline-warning btn-lg btn-block">Change Password</button>
                <small class="font-italic text-center form-text text-muted">© Copyright 2020 By.Puntakarn</small>
            </form>
        </div>
        <div class="col-sm-4">
        </div>
    </div>
{% endblock content %}

search/templates/search/creator.html
{% extends "public_base.html" %}
{% block content %}
{% load static %}
    <div class="row">
        <div class="form-group col-md-12 p-3 mt-3 card shadow bg-white rounded" style="width: 20rem;">
            <div class="row p-3">
                <div class="col-md-6 text-center">
                    <img src="{% static '/photo/pro.jpg' %}" class="img-thumbnail" width="400px">
                </div>
                <div class="col-md-6">
                    <h2><b>Profile</b></h2>
                    <p>Puntakarn Kaewsanghan ( 61070139 )<br>
                       Faculty of Information Technology students<br>
                       King Mongkut's Institute of Technology Ladkrabang</p>
                    <h6><b>Skill</b></h6>
                    <ul>
                        <li>Django</li>
                        <li>Python</li>
                        <li>HTML</li>
                        <li>Bootstrap</li>
                    </ul>
                   <h6><b>Professor</b></h6>
                   <p>ดร.บัณฑิต ฐานะโสภณ<br>อาจารย์ คณะเทคโนโลยีสารสนเทศ<br>สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

search/templates/search/edit_blog.html
{% extends "public_base.html" %}
{% block content %}
    <form action="{% url 'edit_blog' blog.id %}" method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="form-group col-md-12 p-3 mt-3 card shadow bg-white rounded">
                <div class="row p-4 mr-1 ml-1 mt-1 mb-1">
                    <div class="col-md-12">
                        <h2>Edit Blog</h2>
                    </div>
                    <div class="col-md-12">
                        <div class="row p-4">
                            <div class="col-md-1 text-right mt-1">
                                <h4>Title</h4>
                            </div>
                            <div class="col-md-11">
                                <input type="text" class="form-control" name="title" value="{{ blog.title }}" required>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="row m-3">
                            <textarea class="form-control" id="exampleFormControlTextarea1" rows="10" name="content" required>{{ blog.content }}</textarea>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="row m-3">
                            <div class="col-md-12 text-right">
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="checkbox" name="checkbox" value="Hide"
                                        {% comment %} เช็คว่าบทความถูกซ่อนหรือแสดงอยู่ {% endcomment %}
                                        {% if blog.status == False %}
                                            checked
                                        {% endif %} >
                                        {% comment %} -------------------------- {% endcomment %}
                                    <label class="form-check-label" for="inlineRadio1">ซ่อนบทความ</label>
                                </div>
                                <button type="submit" class="btn btn-outline-warning">แก้ไขเสร็จสิ้น</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock content %}

search/templates/search/edit_com.html
{% extends "public_base.html" %}
{% block content %}
<form action="{% url 'edit_com' com.id %}" method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="form-group col-md-12 p-3 mt-3 card shadow bg-white rounded" style="width: 20rem;">
            <div class="row p-3 mr-1 ml-1 mt-1 mb-1">
                <div class="col-md-6">
                    <h3>{{ com.post_id.title }}</h3>
                </div>
                <div class="col-md-12">
                    <hr>
                    <p>{{ com.post_id.content }}</P>
                    <small class="font-italic text-right form-text text-muted">{{ com.post_id.create_time }}</small>
                </div>
            </div>
        </div>
        <div class="form-group col-md-12 p-3 card shadow bg-white rounded" style="width: 20rem;">
            <div class="row p-3 mr-1 ml-1">
                <div class="col-md-12 mb-2">
                    <h5>Edit Comment</h5>
                </div>
                <div class="col-md-8 mb-2">
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="content" required>{{ com.content }}</textarea>
                </div>
                <div class="col-md-8">
                    <div class="row">
                        <div class="col-md-6 mb-2">
                            <small class="font-italic form-text text-muted">โดย {{ com.user_id.username }}</small>
                        </div>
                        <div class="col-md-6 mb-2 text-right">
                            <button type="submit" class="btn btn-outline-warning mb-2">บันทึก</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
 </form>
{% endblock content %}

search/templates/search/index.html
{% extends "public_base.html" %}
{% block content %}
{% load static %}
<div class="row mt-4 mb-1">
    <div class="col-sm-12">
        <form action="{% url 'index' %}" class="form-inline" method="POST">
            {% csrf_token %}
            <div class="form-group mx-sm-2 mb-2">
                <input type="text" class="form-control" placeholder="ค้นหาบทความ" name="blog" required>
            </div>
            <button type="submit" class="btn btn-outline-warning mb-2">ค้นหา</button>
        </form>
    </div>
    {% comment %} ---------- เมื่อมีการส่งค่าการค้นหากลับมา ---------- {% endcomment %}
    {% if blog_name %}
        {% if post_all.count > 0 %}
            <div class="col-sm-12 ml-3 mb-2" style="margin-top: -10;">
                {{ blog_name }}
            </div>
        {% else %}
            <div class="col-sm-12 ml-3 mb-2" style="margin-top: -10;">
                ไม่พบบทความ
            </div>
        {% endif %}
    {% endif %}
    {% comment %} ---------------------------------------------= {% endcomment %}
</div>
<div class="row">
    {% for post in post_all %}
        <div class="col-sm-3">
            <div class="card shadow p-2 mb-5 bg-white rounded" style="width: 16.2rem; height: 16rem;">
                <div class="card-body">
                    <h5 class="card-title"
                        style="height:1.4em; white-space: wrap; overflow: hidden; text-overflow: ellipsis;">
                        <b>{{ post.title }}</b></h5>
                    <p class="card-text"
                        style="font-size: 14px; height:9em; white-space: wrap; overflow: hidden; text-overflow: ellipsis;">
                        {{ post.content }}</p>
                    <div class="row">
                        <div class="col-sm-6 mb-3" style="margin-top: -6;">
                            {% comment %} ------------------------------------- ให้แสดงเฉพาะ Blogger เท่านั้น ------------------------------------- {% endcomment %}
                            {% if request.user.is_superuser %}
                                {% for c in com %}
                                    {% if c.0 == post.id %}
                                        {{ c.1 }}
                                    {% endif %}
                                {% endfor %}

                                {% if post.status == False %}
                                    <a href="{% url 'status' post.id %}" onclick="show()"><img src="{% static '/photo/hide.png' %}" width="30.5px"></a>
                                {% else %}
                                    <a href="{% url 'status' post.id %}" onclick="hide()"><img src="{% static '/photo/see.png' %}" width="27.5px"></a>
                                {% endif %}
                                    <a href="{% url 'post_remove' post.id %}" onclick="remove()"><img src="{% static '/photo/remove.png' %}" width="17px"></a>
                            {% endif %}
                            {% comment %} ------------------------------------- ให้แสดงเฉพาะ Blogger เท่านั้น ------------------------------------- {% endcomment %}
                        </div>
                        <div class="col-sm-6 text-right">
                            <a href="{% url 'blog' post.id %}" class="badge badge-pill badge-warning">อ่านเพิ่มเติม</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% comment %} ------------------------------------ เฉพาะผู้ที่มีสิทธิ์เพิ่มบทความเท่านั้น ------------------------------------ {% endcomment %}
{% if perms.blogger.add_post %}
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4 mb-4" style="margin-top: -4;">
            <a href="{% url 'post' %}" type="button" type="button" class="btn btn-warning btn-lg btn-block">เขียนบทความใหม่</a>
        </div>
        <div class="col-4"></div>
    </div>
{% endif %}
{% comment %} ----------------------------------------------------------------------------------------------------- {% endcomment %}
<script>
    function remove() {
        alert('ลบบทความสำเร็จ')
    }
    function show() {
        alert('แสดงบทความสำเร็จ')
    }
    function hide() {
        alert('ซ่อนบทความสำเร็จ')
    }
</script>
{% endblock %}